markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/into-clojure/into-clojure.github.io
help_url: https://github.com/into-clojure/into-clojure.github.io
google_analytics_id: UA-42657236-2
timezone: Europe/Zurich
